version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sudoku_masters
    ports:
      - "3306:3306"
    networks:
      - sm-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - ./db/mysql:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase:4.24.0
    networks:
      - sm-network
    volumes:
      - ./db/migrations:/db
    command: --defaultsFile=/db/liquibase.properties update
    environment:
      INSTALL_MYSQL: true
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass password
    networks:
      - sm-network
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data

  api:
    build: 
      dockerfile: api-server/Dockerfile
    environment:
      - DB_URL=mysql+aiomysql://root:password@mysql:3306/sudoku_masters
      - REDIS_URL=redis://:password@redis:6379
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - PUBLIC_KEY_PATH=/app/rsa-keys/signature.pub
      - PRIVATE_KEY_PATH=/app/rsa-keys/signature.pem
      - JWT_ALGORITHM=RS256
    networks:
      - sm-network
    ports:
      - "8080:8080"
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis:
        condition: service_started

  generator:
    build: 
      dockerfile: generator/Dockerfile
    networks:
      - sm-network
    depends_on:
      liquibase:
        condition: service_completed_successfully

networks:
  sm-network:
    name: "sm-network"
