version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sudoku_masters
    ports:
      - "3306:3306"
    networks:
      - sm-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  liquibase:
    image: liquibase/liquibase:4.19.0
    networks:
      - sm-network
    volumes:
      - ./db/migrations:/db
    command: --defaultsFile=/db/liquibase.properties update
    environment:
      INSTALL_MYSQL: true
    depends_on:
      mysql:
        condition: service_healthy

networks:
  sm-network:
    name: "sm-network"
